### ISSUE TITLE
Some addition and enhancement on the DS-Algo Notes

### ISSUE THREAD

**Issue by anonyda** [adityanjr/code-DS-ALGO#15]
Hi @adityanjr, 

I was just going through DS-Algo Notes folder, and I must say, It is a very good effort. But I think some concepts need more explanation and enhancement. I also believe that explaining the actual code through pseudocode might be very efficient.

Please let me know what do you think about that. If your thoughts align with mine, I would like to work on it.

**Comment by adityanjr** [comment]
I was too thinking to update them. It would be great if you like to work on them 😃
