### ISSUE TITLE
HacktoberFest 2020

### ISSUE THREAD

**Issue by adityanjr** [adityanjr/code-DS-ALGO#3]
Instructions in README of this repo.

**Comment by Rishabh186** [comment]
Please provide description

**Comment by adityanjr** [comment]
Head over to README.md of this repo, and contribute 😇

**Comment by shivajipotnuru** [comment]
yeah I will be working on it!!

**Comment by adityanjr** [comment]
Nice, but be careful to choose right folder. And be organised. Thank You 🎈

**Comment by shivajipotnuru** [comment]
yeah i want to add coding ninjas data structures in java Questions and solutions it's okay right ?

**Comment by adityanjr** [comment]
Good to go 👌

**Comment by shivajipotnuru** [comment]
I had added the folder and sent you pull request, there are no conflicts accept my request  👍 :)

**Comment by adityanjr** [comment]
Done 👍

**Comment by InfamousBolt** [comment]
Can I add python implementation of the code that's already there? Like in the data structures directory most of the file are in C++

**Comment by adityanjr** [comment]
Yes, you can.

**Comment by Harshitbhatt69** [comment]
Hey there, can i contribute in gaming section? Everything else is looking completed already.

**Comment by Harshitbhatt69** [comment]
And LIVE IPL score card program too?

**Comment by adityanjr** [comment]
Yes, looks awesome 👓

**Comment by InfamousBolt** [comment]
Hey @adityanjr, could you please accept my PR :)

**Comment by adityanjr** [comment]
@InfamousBolt already did ✔

**Comment by InfamousBolt** [comment]
Oh! So will it still require 7 days for my PR to get validated in Hactoberfest? 
PS: Sorry, it's my first time :/

**Comment by InfamousBolt** [comment]
![image](https://user-images.githubusercontent.com/47386839/94836352-84ed0800-0430-11eb-84a9-006c96a3e6e3.jpeg)

Because am still getting this 👆🤷‍♂️

**Comment by Harshitbhatt69** [comment]
> Yes, looks awesome 👓

kindly merge branch, i have created new folder for snackgame.cpp too.
PEACE 👍🏻

**Comment by adityanjr** [comment]
@InfamousBolt Yes it is valid. and should be approved in a week.

**Comment by Harshita248** [comment]
I would like to contribute in the code

**Comment by adityanjr** [comment]
Well, add the codes, you dont find in the repo. All topics are seperated in their respective folders.

**Comment by Harshita248** [comment]
okay @adityanjr and you have to add "hacktoberfest-accepted" label after merging the pr .Thank you : )
